apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ecsdemo-frontend
  namespace: apps
spec:
  hosts:
  - ecsdemo-frontend.apps.svc.cluster.local
  http:
  - route:
    - destination:
        host: ecsdemo-frontend