apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-istio-gateways
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./gitops/target-apps/infrastructure/istio-eastwest-gateway
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: istio-eastwestgateway
      namespace: istio-system
  dependsOn: 
    - name: infrastructure-istio-control-plane