apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-istio-base
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/source-apps/infrastructure/istio-base
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system