kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: istio
networking:
  apiServerAddress: "0.0.0.0"
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
- role: control-plane
- role: worker