kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: source-apps
networking:
  apiServerAddress: "0.0.0.0"
  podSubnet: "10.245.0.0/16"
  serviceSubnet: "10.97.0.0/16"
nodes:
- role: control-plane
- role: worker