kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: target-apps
networking:
  apiServerAddress: "0.0.0.0"
  podSubnet: "172.26.0.0/16"
  serviceSubnet: "100.66.0.0/16"
nodes:
- role: control-plane
- role: worker