apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: istiod
      version: '1.21.*'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 5m
  releaseName: istiod
  targetNamespace: istio-system
  install:
    createNamespace: true