apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  values:
    global:
      meshID: mesh-default
      multiCluster:
        clusterName: target-apps
      network: network-default