apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-metallb
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./gitops/target-apps/infrastructure/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system