apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-metallb-config
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./gitops/source-apps/infrastructure/metallb-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn: 
    - name: infrastructure-metallb-base