apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps2
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/target-apps/apps2
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-istio-eastwest-gateway