apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: apps2
  labels:
    app: app2
    service: app2
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: app2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: apps2
  labels:
    app: app2
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: nginx:latest
        resources:
          requests:
            cpu: "30m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80