---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: metallb
      version: '0.14.*'
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 1m
  releaseName: metallb
  targetNamespace: metallb-system
  install:
    createNamespace: true

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 172.18.201.0-172.18.201.255

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system