apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: base
      version: '1.21.*'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1m
  releaseName: istio-base
  targetNamespace: istio-system
  install:
    createNamespace: true

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  releaseName: istiod
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: istiod
      version: '1.21.*'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1m
  values:
    defaults:
      pilot:
        autoscaleEnabled: false
    global:
      meshID: mesh-default
      multiCluster:
        enabled: true
        clusterName: istio
      network: network-default
    meshConfig:
      defaultConfig:
        proxyMetadata:
          ISTIO_META_DNS_CAPTURE: "true"
          ISTIO_META_DNS_AUTO_ALLOCATE: "true"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system
spec:
  dependsOn:
    - name: istiod
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: gateway
      version: '1.21.*'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1m
  releaseName: istio-ingressgateway
  targetNamespace: istio-system
  values:
    service:
      type: NodePort
    defaults:
      autoscaling:
        enabled: false
    networkGateway: network-default

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kiali
  namespace: flux-system
spec:
  dependsOn:
    - name: istiod
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: kiali-server
      version: '1.82.*'
      sourceRef:
        kind: HelmRepository
        name: kiali
      interval: 1m
  releaseName: kiali
  targetNamespace: istio-system

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: istiod
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: prometheus
      version: '25.19.*'
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 1m
  releaseName: prometheus
  targetNamespace: istio-system