apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: istiod
      version: '1.21.*'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 5m
  releaseName: istiod
  targetNamespace: istio-system
  values:
    global:
      istiod:
        enableAnalysis: true
      meshID: mesh-default
      multiCluster:
        enabled: true
        clusterName: source-apps
      network: network-default
    gateways:
      istio-ingressgateway:
        type: NodePort
    pilot:
      env:
        PILOT_ENABLE_STATUS: true
        PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING: true
    sidecarInjectorWebhook:
      enabled: true