apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-istio-control-plane
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./gitops/istio/infrastructure/istio-control-plane
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istiod
      namespace: istio-system
  dependsOn: 
    - name: infrastructure-istio-base