apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-istio-ingress-gateway
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./gitops/istio/infrastructure/istio-ingress-gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: istio-ingressgateway
      namespace: istio-system
  dependsOn: 
    - name: infrastructure-istio-eastwest-gateway