apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: tools-ingressgateway
  namespace: istio-system
spec:
  profile: empty
  components:
    ingressGateways:
      - name: tools-ingressgateway
        namespace: istio-system
        enabled: true
        label:
          istio: ingressgateway
          app: tools-ingressgateway
        k8s:
          service:
            type: NodePort
        values:
          gateways:
            istio-ingressgateway:
              injectionTemplate: gateway

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: tools-gateway
  namespace: tools
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    hostname: "ecsdemo-frontend.batatinha.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: tools

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http
  namespace: tools
spec:
  parentRefs:
  - name: tools-gateway
  hostnames: ["ecsdemo-frontend.batatinha.com"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /status
    backendRefs:
    - name: ecsdemo-frontend
      port: 80