apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: istiooperators.install.istio.io
  labels:
    release: istio
spec:
  conversion:
    strategy: None
  group: install.istio.io
  names:
    kind: IstioOperator
    listKind: IstioOperatorList
    plural: istiooperators
    singular: istiooperator
    shortNames:
    - iop
    - io
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Istio control plane revision
      jsonPath: .spec.revision
      name: Revision
      type: string
    - description: IOP current state
      jsonPath: .status.status
      name: Status
      type: string
    - description: 'CreationTimestamp is a timestamp representing the server time
        when this object was created. It is not guaranteed to be set in happens-before
        order across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
        lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart: 
    spec:
      chart: manifests/charts/istio-operator
      sourceRef:
        kind: GitRepository
        name: istio
      interval: 5m
  releaseName: istio-operator
  targetNamespace: istio-system


# apiVersion: helm.toolkit.fluxcd.io/v2beta2
# kind: HelmRelease
# metadata:
#   name: istio-base
#   namespace: flux-system
# spec:
#   interval: 1m
#   timeout: 5m
#   chart:
#     spec:
#       chart: base
#       version: '1.21.*'
#       sourceRef:
#         kind: HelmRepository
#         name: istio
#       interval: 1m
#   releaseName: istio-base
#   targetNamespace: istio-system
#   install:
#     createNamespace: true

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta2
# kind: HelmRelease
# metadata:
#   name: istiod
#   namespace: flux-system
# spec:
#   releaseName: istiod
#   targetNamespace: istio-system
#   dependsOn:
#     - name: istio-base
#   interval: 1m
#   timeout: 5m
#   chart:
#     spec:
#       chart: istiod
#       version: '1.21.*'
#       sourceRef:
#         kind: HelmRepository
#         name: istio
#       interval: 1m
#   values:
#     defaults:
#       pilot:
#         autoscaleEnabled: false
#     global:
#       meshID: mesh-default
#       multiCluster:
#         enabled: true
#         clusterName: source-apps
#       network: network-default
#     meshConfig:
#       defaultConfig:
#         proxyMetadata:
#           ISTIO_META_DNS_CAPTURE: "true"
#           ISTIO_META_DNS_AUTO_ALLOCATE: "true"
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta2
# kind: HelmRelease
# metadata:
#   name: istio-ingressgateway
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: istiod
#   interval: 1m
#   timeout: 5m
#   chart:
#     spec:
#       chart: gateway
#       version: '1.21.*'
#       sourceRef:
#         kind: HelmRepository
#         name: istio
#       interval: 1m
#   releaseName: istio-ingressgateway
#   targetNamespace: istio-system
#   values:
#     profile: demo
#     defaults:
#       autoscaling:
#         enabled: false
#     networkGateway: network-default

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kiali
  namespace: flux-system
spec:
  dependsOn:
    - name: istiod
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: kiali
      version: '1.42.*'
      sourceRef:
        kind: HelmRepository
        name: kiali
      interval: 1m
  releaseName: kiali
  targetNamespace: istio-system
  values:
    external_services:
      prometheus:
        url: "http://prometheus-server.istio-system/"

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: istiod
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: prometheus
      version: '25.19.*'
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 1m
  releaseName: prometheus
  targetNamespace: istio-system
