apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-istio-base
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./gitops/istio/infrastructure/istio-base
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true