apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tools
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/istio/infrastructure/tools
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-istio-eastwest-gateway