apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 1m
  timeout: 1m
  chart:
    spec:
      chart: base
      version: '1.21.*'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1m
  releaseName: istio-base
  targetNamespace: istio-system
  install:
    createNamespace: true