apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  values:
    global:
      meshID: mesh-default
      multiCluster:
        clusterName: istio
      network: network-default
    gateways:
      istio-ingressgateway:
        type: NodePort