apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kiali
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://kiali.org/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kiali
  namespace: flux-system
spec:
  interval: 11m
  timeout: 10m
  chart:
    spec:
      chart: kiali-server
      version: '1.81.*'
      sourceRef:
        kind: HelmRepository
        name: kiali
      interval: 10m
  releaseName: kiali
  targetNamespace: istio-system
  values:
    auth:
      strategy: "anonymous"
    # external_services:
    #   prometheus:
    #     url: "http://prometheus-server.istio-system/"
# kubectl port-forward svc/kiali 20001:20001 -n istio-system