apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kiali
  namespace: flux-system
spec:
  interval: 11m
  timeout: 10m
  chart:
    spec:
      chart: kiali
      version: '1.42.*'
      sourceRef:
        kind: HelmRepository
        name: kiali
      interval: 10m
  releaseName: kiali
  targetNamespace: istio-system
  values:
    external_services:
      prometheus:
        url: "http://prometheus-server.istio-system/"
