apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 11m
  timeout: 10m
  chart:
    spec:
      chart: prometheus
      version: '25.19.*'
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 10m
  releaseName: prometheus
  targetNamespace: istio-system
  values:
    server:
      persistentVolume:
        enabled: false